// Package lock reads and writes owfeed.lock.
//
// The lockfile holds the facts owfeed derived rather than the ones a human wrote:
// which point release, which architectures, which toolchain. It is committed and
// reviewed, so upstream adding an architecture arrives as a line in a pull request
// that someone approves, not as a silent change in what a feed publishes.
package lock

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// Version is the lockfile format version.
const Version = 1

// Name is the conventional filename, beside owfeed.yml.
const Name = "owfeed.lock"

// Lock is a parsed owfeed.lock.
type Lock struct {
	Version   int       `yaml:"version"`
	Releases  []Release `yaml:"releases"`
	Toolchain Toolchain `yaml:"toolchain"`
	Keyring   *Keyring  `yaml:"keyring,omitempty"`
}

// Keyring records which signing key the published keyring package carries, and at
// which version.
//
// It is here rather than derived on the spot because the version has to satisfy two
// things at once: change when the key changes, and never go backwards. A version
// computed from the key alone manages the first and fails the second — key identities
// are hashes, so the next one is as likely to sort below the current as above, and a
// keyring that goes backwards is a rotation that no router installs.
//
// Recorded, so a rotation shows up as a diff somebody approves rather than as a
// number that moved on its own. `owfeed lock --update` writes it; `--frozen-lock`
// makes a key that disagrees with it a hard failure, which is what turns "the signing
// key changed under CI" from a silent republish into a stopped build.
type Keyring struct {
	// Identity is the signing key the recorded version belongs to.
	Identity string `yaml:"identity"`
	// Version is the keyring package's version, e.g. "1.2-r1".
	Version string `yaml:"version"`
}

// Release records what was derived for one release line.
type Release struct {
	Line  string `yaml:"line"`
	Point string `yaml:"point"`
	// Source is where Arches came from, so the derivation can be re-checked by hand.
	Source string   `yaml:"source"`
	Arches []string `yaml:"arches"`
}

// Toolchain pins what built the feed.
type Toolchain struct {
	// SDKRelease is the point release whose host apk is used. Never SNAPSHOT: those
	// tarballs are rotated on the mirrors, so a recorded checksum can legitimately
	// stop matching.
	SDKRelease string `yaml:"sdk-release"`
	APKTools   string `yaml:"apk-tools"`
	// KeyringCommit is the openwrt/keyring commit the SDK signing keys were pinned
	// at, recorded so a rotation upstream is visible as a diff.
	KeyringCommit string `yaml:"keyring-commit,omitempty"`
}

const header = `# Generated by owfeed. Commit this file.
#
# It records what owfeed derived rather than what you wrote: an architecture
# appearing or disappearing upstream shows up here as a reviewable diff instead of
# silently changing what your feed publishes. Refresh it with ` + "`owfeed lock --update`" + `.
`

// Load reads a lockfile.
func Load(path string) (*Lock, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var l Lock
	dec := yaml.NewDecoder(strings.NewReader(string(b)))
	dec.KnownFields(true)
	if err := dec.Decode(&l); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	if l.Version != Version {
		return nil, fmt.Errorf("%s: lock format version %d, this owfeed writes version %d", path, l.Version, Version)
	}
	return &l, nil
}

// Save writes a lockfile, replacing any existing one atomically so an interrupted
// run cannot leave a half-written lock that the next run would read as truth.
func Save(path string, l *Lock) error {
	l.Version = Version
	l.normalise()

	body, err := yaml.Marshal(l)
	if err != nil {
		return err
	}

	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".owfeed.lock-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())

	if _, err := tmp.WriteString(header); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(body); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmp.Name(), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}

// normalise puts the file in a stable order, so two runs over the same facts
// produce the same bytes and a diff only ever shows real changes.
func (l *Lock) normalise() {
	sort.Slice(l.Releases, func(i, j int) bool { return l.Releases[i].Line < l.Releases[j].Line })
	for i := range l.Releases {
		sort.Strings(l.Releases[i].Arches)
	}
}

// Release returns the entry for a release line.
func (l *Lock) Release(line string) (Release, bool) {
	for _, r := range l.Releases {
		if r.Line == line {
			return r, true
		}
	}
	return Release{}, false
}

// ErrStale reports that the lockfile disagrees with freshly derived facts.
var ErrStale = errors.New("owfeed.lock is out of date")

// StaleError carries the difference, so the message says what changed rather than
// that something did.
type StaleError struct {
	Path    string
	Changes []string
}

func (e *StaleError) Error() string {
	return fmt.Sprintf("%s is out of date:\n  %s\n  run `owfeed lock --update` and review the diff",
		e.Path, strings.Join(e.Changes, "\n  "))
}

func (e *StaleError) Unwrap() error { return ErrStale }

// Check compares a lockfile against freshly derived facts and returns a StaleError
// describing every difference, or nil.
//
// This is what `--frozen-lock` enforces in CI. A new architecture upstream is a
// good thing and still must not change what a release publishes without a human
// seeing it: the feed's contents are part of its contract with subscribers.
func Check(path string, have, want *Lock) error {
	changes := Diff(have, want)
	if len(changes) == 0 {
		return nil
	}
	return &StaleError{Path: path, Changes: changes}
}

// Diff describes how want differs from have, in a form meant to be read.
func Diff(have, want *Lock) []string {
	var out []string
	if have == nil {
		return []string{"there is no lockfile yet"}
	}

	byLine := map[string]Release{}
	for _, r := range have.Releases {
		byLine[r.Line] = r
	}
	seen := map[string]bool{}

	for _, w := range want.Releases {
		seen[w.Line] = true
		h, ok := byLine[w.Line]
		if !ok {
			out = append(out, fmt.Sprintf("+ release line %s (%d architectures)", w.Line, len(w.Arches)))
			continue
		}
		if h.Point != w.Point {
			out = append(out, fmt.Sprintf("~ %s point release %s -> %s", w.Line, h.Point, w.Point))
		}
		for _, a := range added(h.Arches, w.Arches) {
			out = append(out, fmt.Sprintf("+ %s %s", w.Line, a))
		}
		for _, a := range added(w.Arches, h.Arches) {
			// A disappearing architecture is not deleted from the published tree
			// here. Subscribers still have its name in their .list file, and a feed
			// that answers 404 breaks their `apk update` rather than their upgrade.
			out = append(out, fmt.Sprintf("- %s %s (no longer published upstream)", w.Line, a))
		}
	}
	for _, h := range have.Releases {
		if !seen[h.Line] {
			out = append(out, fmt.Sprintf("- release line %s", h.Line))
		}
	}

	if have.Toolchain.SDKRelease != want.Toolchain.SDKRelease && want.Toolchain.SDKRelease != "" {
		out = append(out, fmt.Sprintf("~ SDK %s -> %s", have.Toolchain.SDKRelease, want.Toolchain.SDKRelease))
	}
	if want.Toolchain.APKTools != "" && have.Toolchain.APKTools != want.Toolchain.APKTools {
		out = append(out, fmt.Sprintf("~ %s -> %s", have.Toolchain.APKTools, want.Toolchain.APKTools))
	}
	return out
}

// added returns the entries of b that are not in a.
func added(a, b []string) []string {
	in := make(map[string]bool, len(a))
	for _, s := range a {
		in[s] = true
	}
	var out []string
	for _, s := range b {
		if !in[s] {
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}
