name: probe
on:
  workflow_call:
jobs:
  probe:
    runs-on: ubuntu-latest
    environment: feed
    steps:
      - env:
          K: ${{ secrets.OWFEED_SIGN_KEY }}
          U: ${{ secrets.OWFEED_USIGN_KEY }}
        run: |
          echo "var:    [${{ vars.PROBE }}]"
          echo "repo:   ${{ github.repository }}"
          echo "signkey length: ${#K}"
          echo "usignkey length: ${#U}"
